namespace:
  name: prod
 
service:
  port: 7111
  targetPort: 3111
  protocol: TCP
  type: ClusterIP

image:
  repository: sergiustartsmall/techtrends 
  tag: latest
  pullPolicy: Always

replicaCount: 5

resources:
  requests:
    cpu: 350m
    memory: 128Mi
  limit:
    cpu: 500m
    memory: 256Mi

containerPort: 3111

livenessProbe: /healthz

readinessProbe: /healthz
